
server.port: 8080

spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
  datasource:
    dirverClassName: com.mysql.jdbc.Diver
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: ngochoang
